- name: Find Package Paths
      run: |
        echo "LIBROSA_PATH=$(python -c "import librosa; print(librosa.__file__)")" >> $env:GITHUB_ENV
        echo "NUMPY_PATH=$(python -c "import numpy; print(numpy.__file__)")" >> $env:GITHUB_ENV
        echo "SOUNDDEVICE_PATH=$(python -c "import sounddevice; print(sounddevice.__file__)")" >> $env:GITHUB_ENV
        echo "MATPLOTLIB_PATH=$(python -c "import matplotlib; print(matplotlib.__file__)")" >> $env:GITHUB_ENV

    - name: Build with PyInstaller
      run: >-
        pyinstaller --name="Bird Sound Examiner" --windowed --onefile 
        --additional-hooks-dir=. 
        --hidden-import matplotlib
        --hidden-import matplotlib.backends.backend_tkagg
        --hidden-import matplotlib.pyplot
        --hidden-import numpy 
        --hidden-import librosa 
        --hidden-import sounddevice 
        --hidden-import tkinter 
        --hidden-import shutil 
        --hidden-import pyaudio
        --collect-all matplotlib
        --collect-submodules librosa 
        --collect-submodules numpy 
        --collect-submodules sounddevice 
        --add-data "${{ env.LIBROSA_PATH }}:librosa" 
        --add-data "${{ env.NUMPY_PATH }}:numpy" 
        --add-data "${{ env.SOUNDDEVICE_PATH }}:sounddevice" 
        --add-data "${{ env.MATPLOTLIB_PATH }}:matplotlib"
        --add-binary "$(python -c "import sounddevice as sd; print(sd.__file__)"):sounddevice"
        --noupx 
        bird_sounds_filter_app.py
