name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Locate Package Paths
      run: |
        echo "LIBROSA_PATH=$(python -c "import librosa; print(librosa.__path__[0])")" >> $env:GITHUB_ENV
        echo "NUMPY_PATH=$(python -c "import numpy; print(numpy.__path__[0])")" >> $env:GITHUB_ENV
        echo "SOUNDDEVICE_PATH=$(python -c "import sounddevice; print(sounddevice.__file__)")" >> $env:GITHUB_ENV
        echo "MATPLOTLIB_PATH=$(python -c "import matplotlib; print(matplotlib.__path__[0])")" >> $env:GITHUB_ENV
        echo "SOUNDFILE_PATH=$(python -c "import soundfile; print(soundfile.__file__)")" >> $env:GITHUB_ENV

    - name: Build with PyInstaller
      run: >-
        pyinstaller --name="Bird Sound Examiner" --windowed --onefile 
        --additional-hooks-dir=. 
        --hidden-import matplotlib
        --hidden-import matplotlib.backends.backend_tkagg
        --hidden-import matplotlib.pyplot
        --hidden-import numpy 
        --hidden-import librosa 
        --hidden-import sounddevice
        --hidden-import soundfile
        --hidden-import tkinter 
        --hidden-import shutil 
        --collect-all matplotlib
        --collect-submodules librosa 
        --collect-submodules numpy 
        --collect-submodules sounddevice
        --collect-submodules soundfile
        --add-data "${{ env.LIBROSA_PATH }};librosa" 
        --add-data "${{ env.NUMPY_PATH }};numpy" 
        --add-data "${{ env.SOUNDDEVICE_PATH }};sounddevice"
        --add-data "${{ env.MATPLOTLIB_PATH }};matplotlib"
        --add-data "${{ env.SOUNDFILE_PATH }};soundfile"
        bird_sounds_filter_app.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Bird Sound Examiner
        path: dist/Bird Sound Examiner.exe
