name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install problematic packages
      run: |
        pip install librosa numpy matplotlib soundfile sounddevice

    - name: Verify package installation
      run: |
        python -m pip list
        python -c "import librosa; print('librosa version:', librosa.__version__)"
        python -c "import numpy; print('numpy version:', numpy.__version__)"
        python -c "import matplotlib; print('matplotlib version:', matplotlib.__version__)"
        python -c "import soundfile; print('soundfile version:', soundfile.__version__)"
        python -c "import sounddevice; print('sounddevice version:', sounddevice.__version__)"

    - name: Build with PyInstaller
      run: >-
        pyinstaller --name="Bird Sound Examiner" --windowed --onefile 
        --additional-hooks-dir=. 
        --hidden-import matplotlib
        --hidden-import matplotlib.backends.backend_tkagg
        --hidden-import matplotlib.pyplot
        --hidden-import numpy 
        --hidden-import librosa 
        --hidden-import soundfile
        --hidden-import sounddevice
        --hidden-import tkinter 
        --hidden-import shutil 
        --collect-all matplotlib
        --collect-submodules librosa 
        --collect-submodules numpy 
        --collect-submodules soundfile
        --collect-submodules sounddevice
        bird_sounds_filter_app.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Bird Sound Examiner
        path: dist/Bird Sound Examiner.exe
