name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install matplotlib
        pip install pyinstaller
    
    - name: Debug dependencies
      run: |
        pip list
        python -c "import sys; print(sys.path)"
    
    - name: Locate matplotlib
      run: |
        $matplotlibPath = (python -c "import matplotlib; print(matplotlib.__path__[0])")
        echo "MATPLOTLIB_PATH=$matplotlibPath" >> $env:GITHUB_ENV
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --name="Bird Sound Examiner" --windowed --onefile --additional-hooks-dir=. --add-data "$env:MATPLOTLIB_PATH;matplotlib" --hidden-import matplotlib --hidden-import matplotlib.backends.backend_tkagg --hidden-import numpy --hidden-import librosa --hidden-import sounddevice bird_sounds_filter_app.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Bird Sound Examiner
        path: dist/Bird Sound Examiner.exe
