- name: Build with PyInstaller
      run: >-
        pyinstaller --name="Bird Sound Examiner" --windowed --onefile 
        --additional-hooks-dir=. 
        --hidden-import matplotlib
        --hidden-import matplotlib.backends.backend_tkagg
        --hidden-import matplotlib.pyplot
        --hidden-import numpy 
        --hidden-import librosa 
        --hidden-import sounddevice 
        --hidden-import tkinter 
        --hidden-import shutil 
        --hidden-import pyaudio
        --collect-all matplotlib
        --collect-submodules librosa 
        --collect-submodules numpy 
        --collect-submodules sounddevice 
        --exclude-module matplotlib.tests
        --exclude-module numpy.f2py.tests
        --add-binary "$(python -c 'import sounddevice as sd; print(sd._libportaudio_filename)'):./"
        bird_sounds_filter_app.py
