name: Build and Deploy BirdSoundExaminer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build executable with PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --clean --onefile BirdSoundExaminer.py
        continue-on-error: true

      # Optionally, you can upload the build artifacts
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: BirdSoundExaminer
          path: dist/BirdSoundExaminer

