name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r mac-requirements.txt
    
    - name: Build with PyInstaller
      env:
        MACOSX_DEPLOYMENT_TARGET: "10.12"
      run: |
        pyinstaller --name="BirdSoundExaminer" \
                    --windowed \
                    --onefile \
                    --target-architecture universal2 \
                    --osx-bundle-identifier "com.yourdomain.birdsoundexaminer" \
                    bird_sounds_filter_app.py
    
    - name: Check disk space
      run: df -h
    
    - name: Clean up disk space
      run: |
        sudo rm -rf /usr/local/lib/android
        df -h
    
    - name: Create DMG
      run: |
        hdiutil create -size 200m -volname "BirdSoundExaminer" -srcfolder dist/BirdSoundExaminer.app -ov -format UDZO BirdSoundExaminer.dmg
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: BirdSoundExaminer
        path: BirdSoundExaminer.dmg
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: BirdSoundExaminer.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
